### ISSUE TITLE
Who can give me an example? There are already Arduino library files by jonnieZG,Exponential Weighted Moving Average.please give me a examples in arduino

### ISSUE THREAD

**Issue by whgkaiser** [jonnieZG/EWMA#2]
Who can give me an example? There are already Arduino library files by jonnieZG,Exponential Weighted Moving Average.please give me a examples in arduino

**Comment by whgkaiser** [comment]
How does a sensor apply this  EWMA arduino library ? could u give me a example ? thank u very much .

**Comment by jonnieZG** [comment]
Some sensors, like accelerometer or fast photoresistors, give you quite noisy readings, meaning that two consecutive readings usually can differ up to 10%. These spikes make detection of movements (or whatever correlated events) impossible, so in order to smooth them out, you need to use a filter like this one.

Instantiate a filter, find an "alpha" value that meets the best your sampling frequency and noise level (that is something you have to find out by trial and error) and feed it with a sensor readings. Instead of reading the sensor directly, read the filter .output value - and that's all.

I'll add an example one of these days.

**Comment by whgkaiser** [comment]
Thank you very much！Very interesting project.Good luck to you.

发自我的iPhone


------------------ Original ------------------

**Comment by jonnieZG** [comment]
Added in release https://github.com/jonnieZG/EWMA/releases/tag/1.0.1
