### ISSUE TITLE
EwmaT only handles unsigned?

### ISSUE THREAD

**Issue by mike-s123** [jonnieZG/EWMA#3]
This breaks (returns high numbers instead of negatives when the "average" goes negative) when fed negative values.

    EwmaT <long int> diff_ewmat(3, 10, 500); 
    ...
    filtered = diff_ewmat.filter(value); 

This works (add/subtract an offset to keep everything positive):

    EwmaT <long int> diff_ewmat(3, 10, 1000500); 
    ...
    filtered = diff_ewmat.filter(value+1000000)-1000000; 

Sorry, C++ isn't nearly my day job, so maybe I'm expecting too much, but there's nothing to indicate this shouldn't work with signed numbers.

**Comment by jonnieZG** [comment]
We are talking about Arduino and Arduino-like platforms here, right?

Integer-based types (non-floating) are differently implemented on different platforms. On some, an int would be 16 bits, on some it would be 32 etc.  It is much safer and cleaner to use type aliases defined in <Arduino.h> such as "uint8_t" for "unsigned 8-bit integer", "int16_t" for "signed 16-bit integer" etc. That way you will always know what are you dealing with.

You have to know what range of data to expect, and therefore use an appropriate data type, because the overflow can occur each time you add or multiply something. Besides, there is also the additional alphaScale factor. There is no (simple) universal solution for this problem, without making the class big and heavy. 

The proper way of handling these issues is to know the possible input range, to choose a proper type (preferably through type aliases as described before), and to optionally apply a shift - if required.
